org: arthurworkspace
service: valheim-server-handler

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./sls/config/env.yml)}
  iam:
    role: ${file(./sls/config/role.yml)}

plugins:
  - serverless-scriptable-plugin

custom:
  bucketName: ${env:S3_BUCKET_NAME}
  scriptable:
    hooks:
      after:deploy:deploy:
        - echo "Copiando docker-compose.yml para o S3..."
        - aws s3 cp src/docker-compose.yml s3://${self:custom.bucketName}/docker-compose.yml
        - echo "docker-compose.yml copiado com sucesso!"


package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"
    external:
      - "@aws-sdk/*"



functions:
  - ${file(./sls/functions/dns.yml)}

resources:
  - ${file(./sls/resources/EC2.yml)}
  - ${file(./sls/resources/ConfigurationBucket.yml)}