statements:
  - Effect: Allow
    Action:
      - ec2:DescribeInstances
    Resource: "*"

  - Effect: Allow
    Action:
      - route53:ChangeResourceRecordSets
    Resource: "arn:aws:route53:::hostedzone/${env:HOSTED_ZONE_ID}"

  - Effect: Allow
    Action:
      - s3:GetObject
      - s3:PutObject
      - s3:ListBucket
    Resource:
      - "arn:aws:s3:::${env:S3_BUCKET_NAME}/*"
